import json
import os

repo_root = "/home/lion397/codes/image-to-l-system"
nb_path = os.path.join(repo_root, "notebooks", "differentiable_renderer_stability_test.ipynb")

cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# Differentiable Renderer Pipeline & Numerical Stability Test (10 DAP Cowpea)\n",
            "\n",
            "This notebook tests the end-to-end differentiable renderer pipeline and its numerical stability when fitting a 15D organ-node array to a synthetic plant image.\n",
            "\n",
            "### Refined Pipeline Stages:\n",
            "1. **Ground Truth Data Generation**: Generate 10 DAP plant XML & Ground Truth using C++ Helios executable with `-n dap10_groundtruth`.\n",
            "2. **Differentiable Target Rendering & Optimization**: Render ground truth XML into a target image ($I_{\\text{target}}$) using `DifferentiableHeliosRenderer`. Initialize perturbed parameters ($N_{\\text{param}} = N_{\\text{gt}} + \\text{noise}$), optimize via backprop against $I_{\\text{target}}$, and monitor numerical stability (gradient norms, NaN/Inf tracking, parameter bounds, loss trajectory).\n",
            "3. **C++ Helios Re-Rendering & Evaluation**: Export optimized 15D nodes back to XML (`dap10_rerendered.xml`), pass `'xml': 'dap10_rerendered.xml'` in `params.json`, re-render using C++ Helios executable with `-n dap10_rerendered`, and produce a 3-panel comparison figure ($I_{\\text{target}}$ vs $I_{\\text{pred}}$ vs $I_{\\text{rerender}}$)."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Step 0: Environment Setup & Host Display Logic\n",
            "import os\n",
            "import sys\n",
            "import time\n",
            "import json\n",
            "import socket\n",
            "import tempfile\n",
            "import subprocess\n",
            "import math\n",
            "import numpy as np\n",
            "from PIL import Image\n",
            "import matplotlib.pyplot as plt\n",
            "\n",
            "import torch\n",
            "import torch.nn.functional as F\n",
            "\n",
            "repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) if '__file__' in globals() else '/home/lion397/codes/image-to-l-system'\n",
            "if repo_root not in sys.path:\n",
            "    sys.path.insert(0, repo_root)\n",
            "\n",
            "from diffusion_based.models.helios_xml_parser import HeliosXMLParser, OrganNode3D\n",
            "from diffusion_based.models.legacy.helios_xml_writer_track_a import write_organ_nodes_to_xml\n",
            "from diffusion_based.models.legacy.helios_geometry_track_a import nodes_to_geometry_torch\n",
            "from diffusion_based.models.legacy.helios_rasterizer_3d_track_a import HeliosGeometryRasterizer\n",
            "from diffusion_based.models.legacy.differentiable_pipeline_track_a import DifferentiableHeliosRenderer\n",
            "\n",
            "# Requirement 1: Host Display check\n",
            "env = os.environ.copy()\n",
            "hostname = socket.gethostname()\n",
            "if hostname.startswith(\"gpu-\") or \"gpu\" in hostname or \"DISPLAY\" not in env:\n",
            "    env[\"DISPLAY\"] = \":1.0\"\n",
            "    print(f\"[ENV] Host '{hostname}' -> export DISPLAY=:1.0\")\n",
            "else:\n",
            "    print(f\"[ENV] Host '{hostname}', DISPLAY={env.get('DISPLAY')}\")\n",
            "\n",
            "print(f\"PyTorch version: {torch.__version__}\")\n",
            "print(f\"CUDA available:  {torch.cuda.is_available()}\")\n",
            "if torch.cuda.is_available():\n",
            "    print(f\"CUDA Device:     {torch.cuda.get_device_name(0)}\")"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "--- \n",
            "## Stage 1: Generate 10 DAP Ground Truth Data using C++ Helios Executable (-n dap10_groundtruth)\n",
            "\n",
            "We generate a 10 DAP plant XML and reference image using the C++ binary with unique output prefix `-n dap10_groundtruth`."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "DAP = 10\n",
            "SEED = 42\n",
            "OUTPUT_DIR = os.path.join(repo_root, \"notebooks\", \"output_dap10_stability\")\n",
            "os.makedirs(OUTPUT_DIR, exist_ok=True)\n",
            "\n",
            "main_binary = os.path.join(repo_root, \"Digital-Crops\", \"projects\", \"syntheticdata_generation\", \"build\", \"main\")\n",
            "base_params_file = os.path.join(repo_root, \"Digital-Crops\", \"projects\", \"syntheticdata_generation\", \"params.json\")\n",
            "\n",
            "with open(base_params_file, \"r\") as f:\n",
            "    params = json.load(f)\n",
            "\n",
            "params.setdefault(\"camera\", {}).setdefault(\"positioning\", {})[\"azimuth_angle\"] = 0.0\n",
            "params[\"camera\"][\"positioning\"][\"camera_height\"] = 1.0\n",
            "params[\"camera\"][\"positioning\"][\"focusing_plants\"] = True\n",
            "params.setdefault(\"metadata\", {})[\"dap\"] = int(DAP)\n",
            "params[\"metadata\"].pop(\"DAP\", None)\n",
            "\n",
            "# Requirement 2: Unique ground truth output prefix\n",
            "name = \"dap10_groundtruth\"\n",
            "tmp_params_path = os.path.join(OUTPUT_DIR, f\"{name}_params.json\")\n",
            "with open(tmp_params_path, \"w\") as f:\n",
            "    json.dump(params, f, indent=2)\n",
            "\n",
            "cmd = [\n",
            "    main_binary,\n",
            "    \"--renderer\", \"vis\",\n",
            "    \"--save-xml\",\n",
            "    \"--focus-plant\",\n",
            "    \"-n\", name,\n",
            "    \"--dap\", str(DAP),\n",
            "    \"-s\", str(SEED),\n",
            "    \"--output\", OUTPUT_DIR,\n",
            "    \"-f\", tmp_params_path,\n",
            "]\n",
            "\n",
            "print(f\"Executing C++ Helios binary: {' '.join(cmd)}\")\n",
            "t0 = time.time()\n",
            "res = subprocess.run(cmd, cwd=os.path.dirname(main_binary), env=env, capture_output=True, text=True)\n",
            "print(f\"Completed in {time.time()-t0:.2f}s\")\n",
            "\n",
            "gt_xml_path = os.path.join(OUTPUT_DIR, f\"{name}_0000_plant_0000.xml\")\n",
            "gt_img_path = os.path.join(OUTPUT_DIR, f\"{name}_0000_vis.jpeg\")\n",
            "if not os.path.exists(gt_img_path):\n",
            "    gt_img_path = os.path.join(OUTPUT_DIR, f\"{name}_0000.jpeg\")\n",
            "\n",
            "print(f\"Ground Truth XML: {gt_xml_path}\")\n",
            "print(f\"Ground Truth Image: {gt_img_path}\")"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "--- \n",
            "## Stage 2: Differentiable Target Render & 15D Node Optimization\n",
            "\n",
            "Following the simplified test procedure:\n",
            "1. Render the ground truth XML using `DifferentiableHeliosRenderer` to create the input target image ($I_{\\text{target}}$).\n",
            "2. Perturb 15D node parameters ($N_{\\text{param}} = N_{\\text{gt}} + \\text{noise}$).\n",
            "3. Optimize $N_{\\text{param}}$ via backpropagation against $I_{\\text{target}}$ while tracking loss trajectory, gradient norms, NaN/Inf checks, and parameter convergence."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "device = torch.device(\"cuda\" if torch.cuda.is_available() else \"cpu\")\n",
            "IMAGE_SIZE = 256\n",
            "NUM_ITERS = 200\n",
            "LR = 0.01\n",
            "NOISE_SCALE = 0.05\n",
            "\n",
            "# Parse GT XML to 15D organ nodes\n",
            "parser = HeliosXMLParser(gt_xml_path)\n",
            "parser.parse()\n",
            "gt_organ_nodes = parser.get_all_organ_nodes()\n",
            "print(f\"Parsed {len(gt_organ_nodes)} organ nodes from XML.\")\n",
            "\n",
            "gt_nodes_np = np.stack([n.to_15d() for n in gt_organ_nodes], axis=0)\n",
            "gt_nodes_tensor = torch.tensor(gt_nodes_np, dtype=torch.float32, device=device).unsqueeze(0)\n",
            "parents_tensor = torch.tensor([n.parent_idx for n in gt_organ_nodes], dtype=torch.long, device=device).unsqueeze(0)\n",
            "\n",
            "rasterizer = HeliosGeometryRasterizer(image_size=IMAGE_SIZE).to(device)\n",
            "renderer = DifferentiableHeliosRenderer(rasterizer).to(device)\n",
            "\n",
            "# Requirement 3: Render target image using Differentiable Renderer\n",
            "with torch.no_grad():\n",
            "    target_rgba = renderer(gt_nodes_tensor, parents=parents_tensor, focus_plant=True, background=\"ground\")\n",
            "\n",
            "target_rgb_tensor = target_rgba[:, :3].detach()\n",
            "target_rgb_np = target_rgb_tensor[0].permute(1, 2, 0).cpu().numpy().clip(0, 1)\n",
            "\n",
            "# Add perturbation to initial parameters\n",
            "torch.manual_seed(42)\n",
            "nodes_param = gt_nodes_tensor.clone()\n",
            "nodes_param[:, :, :8] += torch.randn_like(nodes_param[:, :, :8]) * NOISE_SCALE\n",
            "nodes_param = nodes_param.detach().requires_grad_(True)\n",
            "\n",
            "optimizer = torch.optim.Adam([nodes_param], lr=LR)\n",
            "history = {\"loss\": [], \"loss_rgb\": [], \"grad_norm\": [], \"nan_count\": 0, \"inf_count\": 0, \"param_err\": []}\n",
            "\n",
            "print(f\"Starting optimization against Differentiable Target Input for {NUM_ITERS} iterations...\")\n",
            "t0 = time.time()\n",
            "for i in range(1, NUM_ITERS + 1):\n",
            "    optimizer.zero_grad()\n",
            "    pred_rgba = renderer(nodes_param, parents=parents_tensor, focus_plant=True, background=\"ground\")\n",
            "    \n",
            "    loss_rgb = F.l1_loss(pred_rgba[:, :3], target_rgb_tensor)\n",
            "    reg_len = F.relu(-nodes_param[:, :, 3]).mean() * 10.0\n",
            "    reg_rad = F.relu(-nodes_param[:, :, 4]).mean() * 10.0\n",
            "    loss = loss_rgb + reg_len + reg_rad\n",
            "    \n",
            "    loss.backward()\n",
            "    \n",
            "    grad = nodes_param.grad\n",
            "    if torch.isnan(grad).any().item() or torch.isnan(pred_rgba).any().item():\n",
            "        history[\"nan_count\"] += 1\n",
            "    if torch.isinf(grad).any().item() or torch.isinf(pred_rgba).any().item():\n",
            "        history[\"inf_count\"] += 1\n",
            "        \n",
            "    grad_norm = grad.norm().item() if grad is not None else 0.0\n",
            "    param_err = (nodes_param.detach() - gt_nodes_tensor).abs().mean().item()\n",
            "    \n",
            "    history[\"loss\"].append(loss.item())\n",
            "    history[\"loss_rgb\"].append(loss_rgb.item())\n",
            "    history[\"grad_norm\"].append(grad_norm)\n",
            "    history[\"param_err\"].append(param_err)\n",
            "    \n",
            "    optimizer.step()\n",
            "    \n",
            "    with torch.no_grad():\n",
            "        nodes_param[:, :, 3].clamp_(min=0.005)\n",
            "        nodes_param[:, :, 4].clamp_(min=0.001)\n",
            "        nodes_param[:, :, 14].clamp_(min=0.0)\n",
            "        \n",
            "    if i == 1 or i % 50 == 0 or i == NUM_ITERS:\n",
            "        print(f\"Iter {i:03d}/{NUM_ITERS:03d} | Loss: {loss.item():.5f} | GradNorm: {grad_norm:.4f} | ParamErr: {param_err:.5f}\")\n",
            "\n",
            "print(f\"Optimization done in {time.time()-t0:.2f}s | NaNs: {history['nan_count']} | Infs: {history['inf_count']}\")"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Plot Optimization Diagnostics\n",
            "fig, axes = plt.subplots(1, 3, figsize=(15, 4))\n",
            "axes[0].plot(history[\"loss\"], label=\"Total Loss\", color=\"crimson\")\n",
            "axes[0].plot(history[\"loss_rgb\"], label=\"RGB L1 Loss\", color=\"navy\", linestyle=\"--\")\n",
            "axes[0].set_title(\"Loss Trajectory (vs Target Diff Render)\")\n",
            "axes[0].set_xlabel(\"Iteration\")\n",
            "axes[0].grid(True, alpha=0.3)\n",
            "axes[0].legend()\n",
            "\n",
            "axes[1].plot(history[\"grad_norm\"], color=\"darkgreen\")\n",
            "axes[1].set_title(\"Gradient Norm (Numerical Stability)\")\n",
            "axes[1].set_xlabel(\"Iteration\")\n",
            "axes[1].set_yscale(\"log\")\n",
            "axes[1].grid(True, alpha=0.3)\n",
            "\n",
            "axes[2].plot(history[\"param_err\"], color=\"purple\")\n",
            "axes[2].set_title(\"15D Parameter MAE vs Ground Truth\")\n",
            "axes[2].set_xlabel(\"Iteration\")\n",
            "axes[2].grid(True, alpha=0.3)\n",
            "\n",
            "plt.tight_layout()\n",
            "plt.show()"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "--- \n",
            "## Stage 3: Re-rendering Optimized XML via C++ Helios Executable (-n dap10_rerendered)\n",
            "\n",
            "We reconstruct the Helios plant XML from the optimized 15D nodes (`dap10_rerendered.xml`), pass `'xml': 'dap10_rerendered.xml'` in `params.json`, re-render using C++ Helios binary with `-n dap10_rerendered`, and display the 3-panel comparison figure."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Convert optimized nodes back to XML\n",
            "opt_nodes_np = nodes_param.detach()[0].cpu().numpy()\n",
            "opt_organ_nodes = []\n",
            "for orig_node, opt_vec in zip(gt_organ_nodes, opt_nodes_np):\n",
            "    new_node = OrganNode3D.from_15d(opt_vec)\n",
            "    new_node.parent_idx = orig_node.parent_idx\n",
            "    new_node.shoot_id = orig_node.shoot_id\n",
            "    new_node.phytomer_idx = orig_node.phytomer_idx\n",
            "    opt_organ_nodes.append(new_node)\n",
            "\n",
            "opt_xml_path = os.path.abspath(os.path.join(OUTPUT_DIR, \"dap10_rerendered.xml\"))\n",
            "write_organ_nodes_to_xml(opt_organ_nodes, opt_xml_path, plant_age=DAP)\n",
            "print(f\"Optimized XML written to: {opt_xml_path}\")\n",
            "\n",
            "# Update params.json to point to optimized XML file\n",
            "rerender_name = \"dap10_rerendered\"\n",
            "params.setdefault(\"field\", {}).setdefault(\"plots\", [{}])[0].setdefault(\"plants\", [{}])[0][\"xml\"] = opt_xml_path\n",
            "tmp_params_path = os.path.join(OUTPUT_DIR, f\"{rerender_name}_params.json\")\n",
            "with open(tmp_params_path, \"w\") as f:\n",
            "    json.dump(params, f, indent=2)\n",
            "\n",
            "cmd = [\n",
            "    main_binary,\n",
            "    \"--renderer\", \"vis\",\n",
            "    \"--focus-plant\",\n",
            "    \"-n\", rerender_name,\n",
            "    \"--dap\", str(DAP),\n",
            "    \"-s\", str(SEED),\n",
            "    \"--output\", OUTPUT_DIR,\n",
            "    \"-f\", tmp_params_path,\n",
            "]\n",
            "\n",
            "subprocess.run(cmd, cwd=os.path.dirname(main_binary), env=env, capture_output=True, text=True)\n",
            "rerender_img_path = os.path.join(OUTPUT_DIR, f\"{rerender_name}_0000_vis.jpeg\")\n",
            "if not os.path.exists(rerender_img_path):\n",
            "    rerender_img_path = os.path.join(OUTPUT_DIR, f\"{rerender_name}_0000.jpeg\")\n",
            "\n",
            "# Load final renders\n",
            "with torch.no_grad():\n",
            "    opt_pred_rgba = renderer(nodes_param, parents=parents_tensor, focus_plant=True, background=\"ground\")\n",
            "opt_pred_rgb = opt_pred_rgba[0, :3].permute(1, 2, 0).cpu().numpy().clip(0, 1)\n",
            "\n",
            "rerender_pil = Image.open(rerender_img_path).convert(\"RGB\").resize((IMAGE_SIZE, IMAGE_SIZE), Image.LANCZOS)\n",
            "rerender_rgb = np.array(rerender_pil, dtype=np.float32) / 255.0\n",
            "\n",
            "# Compute metrics vs Differentiable Target Input\n",
            "mae_pred = float(np.mean(np.abs(opt_pred_rgb - target_rgb_np)))\n",
            "mae_rerender = float(np.mean(np.abs(rerender_rgb - target_rgb_np)))\n",
            "\n",
            "# 3-Panel comparison figure\n",
            "fig, axes = plt.subplots(1, 3, figsize=(15, 5))\n",
            "axes[0].imshow(target_rgb_np)\n",
            "axes[0].set_title(\"Input Target (Diff Render from GT XML)\", fontsize=10, fontweight=\"bold\")\n",
            "axes[0].axis(\"off\")\n",
            "\n",
            "axes[1].imshow(opt_pred_rgb)\n",
            "axes[1].set_title(f\"Optimized Diff Render\\nMAE={mae_pred:.4f}\", fontsize=10, fontweight=\"bold\")\n",
            "axes[1].axis(\"off\")\n",
            "\n",
            "axes[2].imshow(rerender_rgb)\n",
            "axes[2].set_title(f\"Re-rendered (C++ Helios from Opt XML)\\nMAE={mae_rerender:.4f}\", fontsize=10, fontweight=\"bold\")\n",
            "axes[2].axis(\"off\")\n",
            "\n",
            "plt.tight_layout()\n",
            "plt.show()"
        ]
    }
]

nb_content = {
    "cells": cells,
    "metadata": {
        "language_info": {"name": "python"},
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"}
    },
    "nbformat": 4,
    "nbformat_minor": 4
}

with open(nb_path, "w", encoding="utf-8") as f:
    json.dump(nb_content, f, indent=2)

print(f"Successfully generated updated notebook at: {nb_path}")
